// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDAQayAod8wLtLjhM8UjecwQnn8GmIjE',
    appId: '1:406877121867:web:2064b0198168a6f0540cce',
    messagingSenderId: '406877121867',
    projectId: 'todo-12c84',
    authDomain: 'todo-12c84.firebaseapp.com',
    storageBucket: 'todo-12c84.appspot.com',
    measurementId: 'G-D4PVT6Q14Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzLaQj86uNbaoOaHdBgHP4dRpp6NOaFzg',
    appId: '1:406877121867:android:3dcfd22d95eacb7d540cce',
    messagingSenderId: '406877121867',
    projectId: 'todo-12c84',
    storageBucket: 'todo-12c84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrlCrWW3QUvRrKjpuF3KQGvKTpMSzzKQ',
    appId: '1:406877121867:ios:96bdd5bdc7965f75540cce',
    messagingSenderId: '406877121867',
    projectId: 'todo-12c84',
    storageBucket: 'todo-12c84.appspot.com',
    iosClientId: '406877121867-o6pvob4pp0tbs0t4mqjnt61bqd1vdusm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATrlCrWW3QUvRrKjpuF3KQGvKTpMSzzKQ',
    appId: '1:406877121867:ios:96bdd5bdc7965f75540cce',
    messagingSenderId: '406877121867',
    projectId: 'todo-12c84',
    storageBucket: 'todo-12c84.appspot.com',
    iosClientId: '406877121867-o6pvob4pp0tbs0t4mqjnt61bqd1vdusm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
